name: boring_flutter_show_1
description: The Boring Flutter Development Show, Ep. 1

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  url_launcher: "^3.0.3"

  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: '>=0.9.0 <0.11.0'
  built_value_generator: ^6.1.3

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
